# <%= appName %>

<%= appDescription %>

## Requirements

- **Node.js 18+**
- **gulp-cli** installed globally: `npm install -g gulp-cli`

## Getting Started

```bash
npm install
gulp
```

## Task Index

| Task | Description |
|------|-------------|
| `gulp` | Build + watch (full workflow) |
| `gulp build` | Full build |
| `gulp watch` | Watch only (project must be pre-built) |
| `gulp css` | CSS pipeline (Dart Sass → PostCSS → cssnano) |
| `gulp js` | JS pipeline (esbuild) |
| `gulp img` | Image optimisation |
| `gulp nunjucks` | Render Nunjucks templates |
| `gulp deploy --ftp` | Deploy via FTP (configure `.env` first) |
| `gulp deploy --sftp` | Deploy via SFTP (configure `.env` first) |
| `gulp --nomin` | Build with sourcemaps, no minification |
| `gulp --nobs` | Build without starting BrowserSync |

## Author

<%= authorName %>

## Generated by

[create-gulp-khup](https://github.com/uncleSoWise/gulp-khup)
